// Licensed under GPL-3.0 with the App Store exception in LICENSE-EXCEPTION.md.
//
//  AdvancedRulesEngine.swift
//  Nook
//
//  Answers, per frame URL, which cosmetic filter rules apply that a compiled
//  WKContentRuleList cannot express, chiefly procedural filters. Lookup is done
//  by BlockerEngine over adblock-rust (MPL-2.0). The rules are applied in-page
//  by nook-cosmetic.js, which is Nook's own script and needs no build step.
//
//  Plain cosmetic filters do not come through here: the converter turns them
//  into css-display-none entries in the compiled rule list.
//
//  Foundation + WebKit only; nothing here is AppKit-specific.
//

import Foundation
import WebKit
import OSLog

private let log = Logger(subsystem: Bundle.main.bundleIdentifier ?? "Nook", category: "AdvancedRules")

@MainActor
public final class AdvancedRulesEngine {

    /// Prefix on every user script Nook's content blocker owns.
    static let scriptMarker = "// Nook Content Blocker\n"
    /// Prefix on the per-navigation main-frame configuration script.
    static let configScriptMarker = "// Nook Content Blocker Config\n"
    /// WKScriptMessageHandlerWithReply name the runtime uses for subframe lookups.
    public static let messageHandlerName = "nookAdvancedBlocking"

    /// One adblock-rust engine, shared by cosmetic lookup and the dev MCP
    /// check_urls tool. Actor-isolated because the engine pointer is Send but
    /// not Sync.
    public let engine = BlockerEngine()

    // MARK: - Build

    /// Build (or rebuild) the lookup engine from the raw filter rules.
    /// adblock-rust parses filter syntax directly, so there is no intermediate
    /// "advanced rules text" of the kind SafariConverterLib produced, and no
    /// serialized warm start to reuse.
    func build(sources: [FilterListManager.Source]) async {
        await engine.build(sources: sources)
    }

    // MARK: - Lookup

    /// JSON-ready configuration for a frame, or nil when nothing applies.
    /// `topUrl` is the top-level document URL; pass nil for the main frame.
    func configuration(for pageUrl: URL, topUrl: URL?) -> [String: Any]? {
        engine.configuration(for: pageUrl, topUrl: topUrl)
    }

    /// Main-frame fast path: embed the configuration so the runtime applies it synchronously
    /// at document start instead of round-tripping through the message handler.
    /// Always returns a script: `null` when nothing applies, so the runtime skips its async lookup.
    func configUserScript(for pageUrl: URL) -> WKUserScript {
        var json = "null"
        var scriptlets: String?
        if var conf = configuration(for: pageUrl, topUrl: nil) {
            // Carried in the script body, not the config object: it is code, not data.
            scriptlets = conf.removeValue(forKey: "scriptlets") as? String
            if let data = try? JSONSerialization.data(withJSONObject: conf),
               let text = String(data: data, encoding: .utf8) {
                json = text
            }
        }
        // Scriptlets must run here, before nook-cosmetic.js and before the page's
        // own scripts: they patch fetch, XHR and Object as the page will see them.
        // The crate already wraps each call in its own try/catch.
        // The redirect table rides in the same script. Both are per-navigation
        // main-frame state, and a second script would be one more thing to strip
        // and re-add every time the blocker is toggled.
        var redirects = "[]"
        let applicable = Self.redirects(for: pageUrl)
        if !applicable.isEmpty,
           let data = try? JSONSerialization.data(withJSONObject: applicable),
           let text = String(data: data, encoding: .utf8) {
            redirects = text
        }
        var source = Self.configScriptMarker
            + "window.__nookCosmeticConfig = \(json);\n"
            + "window.__nookRedirects = \(redirects);"
        if let scriptlets, !scriptlets.isEmpty {
            source += "\nif(!window.__nookScriptletsRan){window.__nookScriptletsRan=true;try{\n\(scriptlets)\n}catch(e){}}"
        }
        return WKUserScript(
            source: source,
            injectionTime: .atDocumentStart,
            forMainFrameOnly: true
        )
    }

    // MARK: - Redirect table

    /// One entry of `redirects.json`: a `$redirect=` rule reduced to a regex, the
    /// resource that answers it, and the scoping the rule carried.
    private struct RedirectRule: Decodable {
        let p: String
        let r: String
        let d: [String]?
        let x: [String]?
        let t: [String]?
    }

    private struct RedirectTable: Decodable {
        let rules: [RedirectRule]
        let bodies: [String: String]
    }

    /// Generated by scripts/build-redirects.mjs. Read once; most of it never
    /// applies to any given page.
    private static let redirectTable: RedirectTable? = {
        guard let url = Bundle.module.url(forResource: "redirects", withExtension: "json", subdirectory: "Resources"),
              let data = try? Data(contentsOf: url),
              let table = try? JSONDecoder().decode(RedirectTable.self, from: data)
        else {
            log.error("redirects.json missing or malformed; blocked ad scripts will fail loudly")
            return nil
        }
        return table
    }()

    /// A `domain=` entry matches a host and its subdomains, the way the filter
    /// syntax means it. `example.*` is uBO's shorthand for the regional variants.
    private static func hostMatches(_ host: String, _ entry: String) -> Bool {
        if entry.hasSuffix(".*") {
            let stem = String(entry.dropLast(2))
            return host == stem || host.hasSuffix("." + stem) || host.hasPrefix(stem + ".")
                || host.contains("." + stem + ".")
        }
        return host == entry || host.hasSuffix("." + entry)
    }

    /// The rules that can fire on this page, bodies resolved. Most of the 600-odd
    /// rules are domain-scoped, so a page usually gets the global ones and no more.
    static func redirects(for pageUrl: URL) -> [[Any]] {
        guard let table = redirectTable, let host = pageUrl.host?.lowercased() else { return [] }
        var out: [[Any]] = []
        for rule in table.rules {
            if let excluded = rule.x, excluded.contains(where: { hostMatches(host, $0) }) { continue }
            if let domains = rule.d, !domains.contains(where: { hostMatches(host, $0) }) { continue }
            guard let body = table.bodies[rule.r] else { continue }
            out.append([rule.p, body, rule.t ?? []])
        }
        return out
    }

    // MARK: - Static scripts (identical for every webview)

    /// The AdGuard runtime (all frames) plus host-guarded site-specific blockers (main frame).
    static let staticUserScripts: [WKUserScript] = {
        var scripts: [WKUserScript] = []

        if let runtime = bundledSource("nook-cosmetic") {
            scripts.append(WKUserScript(source: scriptMarker + runtime, injectionTime: .atDocumentStart, forMainFrameOnly: false))
        } else {
            log.error("nook-cosmetic.js missing from bundle; cosmetic filtering disabled")
        }
        // Answers known ad URLs with an inert stub so a blocked request does not
        // read as a failure to anti-adblock scripts. All frames: detection runs in
        // subframes too. Removed with the other blocker scripts when a host is
        // allowlisted, so an exempt page is untouched.
        if let stealth = bundledSource("nook-stealth-redirects") {
            scripts.append(WKUserScript(source: scriptMarker + stealth, injectionTime: .atDocumentStart, forMainFrameOnly: false))
        } else {
            log.error("nook-stealth-redirects.js missing from bundle; stealth redirects disabled")
        }
        let siteScripts: [(resource: String, hostPattern: String, setup: String)] = [
            // The feed pruners patch JSON.parse, so they must run before the page's own scripts.
            // facebook-feed-prune is shared with FacebookTweaks; this copy turns on its ad flag.
            ("facebook-feed-prune", #"(^|\.)facebook\.com$"#,
             "(window.__nookFBFilter = window.__nookFBFilter || {}).ads = true;"),
            ("facebook-sponsored-blocker", #"(^|\.)facebook\.com$"#, ""),
            ("instagram-feed-prune", #"(^|\.)instagram\.com$"#, ""),
            ("instagram-sponsored-blocker", #"(^|\.)instagram\.com$"#, ""),
            ("twitter-ad-blocker", #"(^|\.)(twitter\.com|x\.com)$"#, ""),
        ]
        for entry in siteScripts {
            guard let source = bundledSource(entry.resource) else {
                log.warning("Site script missing from bundle: \(entry.resource, privacy: .public)")
                continue
            }
            let guarded = "\(scriptMarker)(function(){ if (!/\(entry.hostPattern)/.test(location.hostname)) return;\n\(entry.setup)\n\(source)\n})();"
            scripts.append(WKUserScript(source: guarded, injectionTime: .atDocumentStart, forMainFrameOnly: true))
        }
        return scripts
    }()

    /// Source of a script shipped inside NookBlocker's resource bundle.
    /// Public because FacebookTweaks shares facebook-feed-prune.js with the blocker.
    public nonisolated static func bundledSource(_ name: String) -> String? {
        guard let url = Bundle.module.url(forResource: name, withExtension: "js", subdirectory: "Resources") else { return nil }
        return try? String(contentsOf: url, encoding: .utf8)
    }
}
