// Licensed under GPL-3.0. See LICENSE.
//
//  ScriptletResources.swift
//  Nook
//
//  The scriptlet resource set handed to adblock-rust. `scriptlets.json` is
//  generated by scripts/build-scriptlets.mjs from the uBlock Origin resources
//  vendored under Packages/NookBlocker/ThirdParty/ubo-scriptlets, and already
//  carries each body base64-encoded, so nothing here parses or rewrites it.
//
//  Those bodies are GPL-3.0 and Raymond Hill's, not Nook's, so Nook's App Store
//  exception cannot reach them. macOS ships them and is distributed only as a
//  notarized DMG. iOS, whose only channel is the App Store, must not. That is
//  the `#if os(iOS)` below, and it is a licence boundary rather than a feature
//  flag: do not make it conditional on anything else.
//

import Foundation
import OSLog

private let log = Logger(subsystem: Bundle.main.bundleIdentifier ?? "Nook", category: "AdvancedRules")

enum ScriptletResources {

    /// JSON array of `adblock::resources::Resource`, or nil when there is none.
    static func json() -> String? {
        #if os(iOS)
        // See the file comment. Without a body every `##+js()` rule resolves to
        // nothing, which is where the whole app stood before September 2026.
        return nil
        #else
        guard let url = Bundle.module.url(forResource: "scriptlets", withExtension: "json", subdirectory: "Resources"),
              let data = try? Data(contentsOf: url),
              let text = String(data: data, encoding: .utf8)
        else {
            log.error("scriptlets.json missing; no scriptlets will run")
            return nil
        }
        log.info("Loaded scriptlet resources (\(data.count, privacy: .public) bytes)")
        return text
        #endif
    }
}
